version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /utils/ansible/ftest/
      - /utils/cq/
      - /
    ignore:
      - dependency-name: "avocado-framework*"
    schedule:
      interval: "cron"
      cronjob: "0 0 1-7,15-21 * 0"  # first and third Sunday
    groups:
      python-packages:
        patterns:
          - "*"
    assignees:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Test-tag: pr,vm \n"

  - package-ecosystem: github-actions
    target-branch: master
    directory: /
    schedule:
      interval: "cron"
      cronjob: "0 0 1-7,15-21 * 0"  # first and third Sunday
    groups:
      gha-versions:
        patterns:
          - "*"
    assignees:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"

  - package-ecosystem: github-actions
    target-branch: release/2.6
    directory: /
    schedule:
      interval: "cron"
      cronjob: "0 0 1-7,15-21 * 0"  # first and third Sunday
    groups:
      gha-versions:
        patterns:
          - "*"
    assignees:
      - daos-stack/actions-watchers
    commit-message:
      prefix: "Doc-only: true \n"
