name: Flake

# Always run on Pull Requests as then this check can be marked as required.
on:
  push:
    branches:
      - amd/isort-config
      - master
      - 'feature/*'
      - 'release/*'
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-22.04
    name: Flake8 check
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3'
      - name: Add parser
        run: echo -n "::add-matcher::ci/daos-flake-matcher.json"
      - name: Add whitespace parser
        run: echo -n "::add-matcher::ci/daos-flakew-matcher.json"
      - name: Add error parser
        run: echo -n "::add-matcher::ci/daos-flakee-matcher.json"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          # W503 and W504 are related as they conflict.  W503 is the preferred style and all code
          # should be using it now.
          ignore: 'W503'
          exclude: 'src/control/vendor,src/client/pydaos/raw'
          max-line-length: '100'
      - name: flake8 Lint on SCons files.
        uses: py-actions/flake8@v2
        with:
          ignore: 'F821,W503,F841'
          max-line-length: '100'
          args: '--filename */SConscript, SConstruct'

  isort:
    name: Isort check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt utils/cq/requirements.txt"
      - name: Run on SConstruct file.
        run: isort --check-only SConstruct
      - name: Run on build files.
        run: find . -name SConscript | xargs isort
