name: Unit testing

on:
  pull_request:

permissions: {}

jobs:
  Build_and_unit_test:
    name: "Build and Run Unit Tests for Ryon"
    runs-on: [self-hosted, wolf]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Request and Provision a Cluster
        timeout-minutes: 7200
        uses: ./.github/actions/provision-cluster
        with:
          condition: true