name: Unit testing

on:
  pull_request:

permissions: {}

jobs:
  Build_and_unit_test:
    name: "Build and Run Unit Tests for Ryon"
    runs-on: [self-hosted, wolf]
    env:
      CONFIG_POWER_ONLY: false
      PRAGMA_SUFFIX: -vm
      OPERATIONS_EMAIL: brian.murrell@intel.com
      TEST_RPMS: true
      JENKINS_URL: https://build.hpdd.intel.com/
      REPOSITORY_URL: https://repo.dc.hpdd.intel.com/
      REMOVE_EXISTING_RPMS: false
      # TODO -- this should be on stable, backedup storage
      ARTIFACTS_URL: file:///scratch/job_repos/
      REPO_FILE_URL: https://artifactory.dc.hpdd.intel.com/artifactory/repo-files/

      CHROOT_NAME: "rocky+epel-8-x86_64"
      DISTRO_NAME: "EL"
      DISTRO_NAME_UPPER: "EL"
      DISTRO_NAME_LOWER: "el"
      DISTRO_VERSION: "8.6"
      DISTRO_VERSION_MAJOR: "8"
      DISTRO_WITH_VERSION: "el8.6"
      OPENMPI: "openmpi"
      LABEL: "ci_vm1"

      DSL_REPO_var: "DAOS_STACK_EL_8_LOCAL_REPO"
      DSG_REPO_var: "DAOS_STACK_EL_8_GROUP_REPO"
      DSA_REPO_var: "DAOS_STACK_EL_8_APPSTREAM_REPO"
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Request and Provision a Cluster
        timeout-minutes: 7200
        uses: ./.github/actions/provision-cluster
        with:
          condition: true