name: Unit Testing Provisioned

env:
  # TODO: we really need to define a list of supported versions (ideally it's no more than 2)
  #       build is done on the lowest version and test on the highest with a "sanity test"
  #       stage done on all versions in the list ecept the highest
  EL8_BUILD_VERSION: 8.6
  EL8_VERSION: 8.8
  EL9_BUILD_VERSION: 9
  EL9_VERSION: 9
  LEAP15_VERSION: 15.5

on:
  pull_request:

concurrency:
  group: unit-testing-provisioned-${{ github.head_ref  || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -ueo pipefail {0}

permissions: {}

jobs:
  Job_1:
    name: Job 1
    runs-on: [self-hosted, wolf]
    permissions:
      statuses: write
      # https://github.com/EnricoMi/publish-unit-test-result-action#permissions
      checks: write
      pull-requests: write
    timeout-minutes: 7200
    env:
      OPERATIONS_EMAIL: ryon.jensen@intel.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 500
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Ryon's Simple Script
        timeout-minutes: 7200
        id: run-test
        run: |
          . ci/gha_functions.sh
          ci/functional/ryon.sh

  Job_2:
    name: Provisioning Job
    runs-on: [self-hosted, wolf]
    permissions:
      statuses: write
      # https://github.com/EnricoMi/publish-unit-test-result-action#permissions
      checks: write
      pull-requests: write
    timeout-minutes: 7200
    env:
      OPERATIONS_EMAIL: ryon.jensen@intel.com
      JENKINS_URL: https://build.hpdd.intel.com/
      LABEL: ci_vm9
      DISTRO_WITH_VERSION: el8
      CHROOT_NAME: "rocky+epel-8-x86_64"
      DISTRO_NAME: "EL"
      DISTRO_VERSION: "8.6"
      COMMIT_STATUS_DISTRO_VERSION: "8"
      STAGE_TAGS: "-vm"
      FTEST_ARG: ""
      DISTRO_NAME_UPPER: "EL"
      DISTRO_NAME_LOWER: "el"
      DISTRO_VERSION_MAJOR: "8"
      OPENMPI: "openmpi"
      DISTRO: "el8"
      DAOS_STACK_el8_LOCAL_REPO: "not_used"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 500
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Request and Provision a Cluster
        timeout-minutes: 7200
        uses: ./.github/actions/provision-cluster
        with:
          condition: env.CP_SKIP_FUNC_TEST-${{ env.DISTRO }} != 'true' && env.CP_SKIP_FUNC_TEST != 'true'
      - name: Run Ryon's Simple Script Again
        timeout-minutes: 7200
        id: run-test
        run: |
          . ci/gha_functions.sh
          ci/functional/ryon.sh