name: Unit testing

on:
  pull_request:

permissions: {}

jobs:
  Run_rocky8_in_docker_on_gcp:
    if: github.repository == 'daos-stack/daos'
    runs-on: [self-hosted, gcp, rocky8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          sparse-checkout-cone-mode: false
